spring.application.name=spring-lens_demo
# Application Name

# Server Configuration
server.port=8080

# Spring Lens Configuration

# Enable Bean Definition Monitoring
spring.lens.bean.definition.enabled=true

# Enable Bean Instance Monitoring
spring.lens.bean.instance.enabled=true

# Include Configuration
spring.lens.bean.include.role-infra=false
spring.lens.bean.include.tool-internal=false


# Exclude Configuration (optional)
spring.lens.bean.exclude.package-patterns=
spring.lens.bean.exclude.classes=